apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yaml

commonLabels:
  app: something
  app2: something2

patchesJson6902:
- target:
    name: id
    kind: Ingress
    group: extensions
    version: v1beta1
  path: host.json