apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: master-node-exporter
  name: master-node-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
