apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: monitoring
subsets:
- addresses:
  - ip: 10.20.0.2
    nodeName: etcd0
  - ip: 10.20.0.3
    nodeName: etcd1 
  - ip: 10.20.0.4
    nodeName: etcd2
  ports:
  - name: metrics
    port: 2379
    protocol: TCP
