apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: etcd
  name: etcd
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/etcd-certs/etcd-ca.crt
      certFile: /etc/prometheus/secrets/etcd-certs/prometheus.crt
      keyFile: /etc/prometheus/secrets/etcd-certs/prometheus.key
      insecureSkipVerify: true
      serverName: etcd
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: etcd
